name: CI

on: [push]

env:
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [ stable, nightly ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        name: Toolchain setup
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: --workspace --all-features --all-targets
      # --all-targets doesn't do doctests
      - uses: actions-rs/cargo@v1
        name: Doctest
        with:
          command: test
          args: --workspace --all-features --doc
