[package]
name = "nippy"
version = "0.5.0-pre"
edition = "2018"
authors = [
    "Michael Lamparski <diagonaldevice@gmail.com>",
    "Pavel Potocek <pavelpotocek@gmail.com>",
]
license = "MIT"
description = "NumPy file format (de-)serialization. Fork of abandoned npy-rs."
repository = "https://github.com/ExpHP/nippy"
homepage = "https://github.com/ExpHP/nippy"
documentation = "https://docs.rs/nippy/"
keywords = ["numpy", "npy", "ndarray"]
categories = ["encoding"]
readme = "README.md"

[package.metadata.docs.rs]
all-features = true

[workspace]
members = [ "derive" ]

[dependencies]
byteorder = "1"
nom = "3"

# NOTE: public dependency, so make sure the doc link to Complex in README.md is kept in sync
num-complex = { version = "0.4", optional = true }

[dependencies.nippy-derive]
path = "derive"
version = "0.5.0-pre"
optional = true
default-features = false

[dev-dependencies]
# For examples ONLY.  We don't want to provide a public interface because ndarray undergoes
# breaking semver bumps very frequently.
ndarray = { version = "0.15"}

[features]
default = []

# Provide #[derive(nippy::Serialize, nippy::Deserialize, nippy::AutoSerialize)].
#
# These are for working with structured arrays (see https://numpy.org/doc/stable/user/basics.rec.html),
# and are not otherwise necessary.
derive = ["nippy-derive"]

# Enables deserialization of the types from num-complex.
complex = ["num-complex"]

[[example]]
name = "plain"

[[example]]
name = "ndarray"

[[example]]
name = "structured"
required-features = ["derive"]

[[example]]
name = "roundtrip"
required-features = ["derive"]

[[test]]
name = "derive_hygiene"
required-features = ["derive"]

[[test]]
name = "roundtrip"
required-features = ["derive"]

[[test]]
name = "serialize_array"
required-features = ["derive"]

[[test]]
name = "nd"
